//Константы (типы) описывающие событие
//Запрос на сервер
export const REQUEST_POKEMON_LOADING = 'REQUEST_POKEMON_LOADING';
export const REQUEST_POKEMON_SUCCESS = 'REQUEST_POKEMON_SUCCESS';
export const REQUEST_POKEMON_FILED = 'REQUEST_POKEMON_FILED';//При ошибке
//Вывод данных
export const ADD_POKEMON_LIST = 'ADD_POKEMON_LIST';
export const ADD_POKEMON = 'ADD_POKEMON';
export const ADD_CURRENT_POKEMON = 'ADD_CURRENT_POKEMON';
export const ADD_POKEMON_ITEM = 'ADD_POKEMON_ITEM';
//Поиск данных
export const REQUEST_POKEMON_ITEM_LOADING = 'REQUEST_POKEMON_ITEM_LOADING';
export const REQUEST_POKEMON_ITEM_SUCCESS = 'REQUEST_POKEMON_ITEM_SUCCESS';
export const REQUEST_POKEMON_ITEM_FILED = 'REQUEST_POKEMON_ITEM_FILED';

